### ISSUE TITLE
Showing arbitrary amperage when charging/discharging

### ISSUE THREAD

**Issue by mastahsee** [TylerWilliamson/BatteryNotification#12]
Model CLT-L29 build 10.0.0.201, showing negative amperage even though plugging/unplugging fast charging and slower charging, arbitrary negative amperage numbers. Got app for testing different charging speeds but it's useless for that.

Update: amperage charging speed update to "correct" amperage seems to have wierd latency. Don't know if it's a bug or feature.

**Comment by TylerWilliamson** [comment]
The app simply shows what your phone is reporting for the amperage. As for the latency, phone batteries charge "smartly" and the amperage is not steady throughout. It seems like you are able to see the "correct" amperage by waiting, so I will close this issue
