### ISSUE TITLE
wrong measurements

### ISSUE THREAD

**Issue by gilcu3** [TylerWilliamson/BatteryNotification#13]
I am using oneplus 7T with Lineage OS. The values shown by the app are in the order of Microampere (µA), while they should be much higher, as the phone is certainly charging. Let me know if I can provide any logs, and how to get them

**Comment by mxvin** [comment]
I mean, what shown on app is using android API, and these values depends on how OEM implement their pm drivers. There's a guidelines from android but not implemented consistently by every vendor.
Maybe that raw value needs to be times by 100 or 1000 that you can adjust yourself, like Ampere app (playstore)?

**Comment by gilcu3** [comment]
I think the values need to be multiplied by -1000, but I am not sure if it always the case.

**Comment by TylerWilliamson** [comment]
This may be a per-device issue. If you find any confirmed documentation for your or other devices, I can include that logic in the calculation. For now, the current calculation will stay the same and I will close this issue.

I will note that it is difficult to estimate the current at a point in time based on what you believe the charger should be outputting. Most modern devices negotiate the voltage and current with the charger based on their own sets of logic and include things such as current charge, battery temperature, battery age, etc. Additionally, there is a bit of delay usually with the data shown in the app and could be up to one minute delayed if "instant updates" are not enabled.
