### ISSUE TITLE
notificación not updating

### ISSUE THREAD

**Issue by paulle** [TylerWilliamson/BatteryNotification#4]
The notification is often not updating, hangs at certain percentage, even when the is much lower, it shows the same value. Same thing showing charging or not charging.
Android 11, Sony Xperia 5

**Comment by TylerWilliamson** [comment]
I have been experiencing this issue myself and I have been working on tracking down and mitigating the issue. I hope to include a fix in the next version.

**Comment by TylerWilliamson** [comment]
I believe I have fixed this in [Version 1.4.3](https://github.com/TylerWilliamson/BatteryNotification/releases/tag/1.4.3). This version is available on GitHub, on Google Play Store for open beta testers, and on F-Droid when they next update their repo. Please test and let me know if you are able to replicate your issue. Otherwise, I will close the issue in about a week. Thanks!

**Comment by paulle** [comment]
Will wait till the new version is on f-droid an when report.
Thank you

Is it possible to display the temperature aside your battery
symbol in the status bar?

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by TylerWilliamson** [comment]
Version 1.4.3 is now available on F-Droid. Could you please test and see if you can replicate the issue?

**Comment by paulle** [comment]
I've v1.43 it seems the issue it's solved.
Thank you

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by paulle** [comment]
I've to correct me.
It's otherwise hanging, even after a restart of the phone.

**Comment by TylerWilliamson** [comment]
Could you take a screenshot of the app? I want to see which settings you are using. Also, are you able to take a bug report when you notice the notification not updating?

**Comment by paulle** [comment]
![Screenshot_20220501-210045](https://user-images.githubusercontent.com/4852079/166160686-1d452c86-6f61-4758-aed0-a4f002a83352.png)
![Screenshot_20220501-205942](https://user-images.githubusercontent.com/4852079/166160697-10f0b993-d87b-42fd-9abe-b415378debf0.png)

**Comment by TylerWilliamson** [comment]
Thank you, that is very helpful. It would appear that both the recurring task every minute (via AlarmManager) and the instant update service are both not functioning. I will investigate

**Comment by paulle** [comment]
Thank you

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by TylerWilliamson** [comment]
Could you check if the service is running? You should be able to list the running services on your phone by going to "Developer Options" and selecting "Running Services". If the service is not running, your phone OS or a "task killer" app may have killed it. Unfortunately, if the service is killed, it may also kill the repeating task.

You can try:
1. Whitelist BatteryNotification in any "Task Killer" app
2. Whitelist BatteryNotification in "Battery Optimization" in Settings
3. Disable the "Update the notification immediately" - this will disable the service and rely on only the recurring task. The notification will update every minute, but there will be no service that can be killed.

I will also investigate making the recurring task's receiver "remote" which should make it less likely to be killed

**Comment by paulle** [comment]
Don't find this option in developer options

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by paulle** [comment]
I tried it now with this configuration
![Screenshot_20220508-153931](https://user-images.githubusercontent.com/4852079/167299065-b33edbfd-a76f-49bc-a77a-98fdbd6935f7.png)
Seems to work, but I will watch for a little more time.
But the battery symbol in the status line is gone.
It would be nice to have the battery symbol in te status with the temperature to have warning when the battery gets hot.

**Comment by paulle** [comment]
![Screenshot_20220508-161203](https://user-images.githubusercontent.com/4852079/167300837-095df0d3-e5b4-4272-8848-c3d97a274e73.png)
I found this option and choosed no optimization, I reactivated
notification immediately for getting back the symbol in the status line. Will see if it works now.

**Comment by paulle** [comment]
It seems to work well with the optimisation off.
Android 11 Sony Xperia 5

**Comment by TylerWilliamson** [comment]
Excellent. Glad to hear it's working well with the optimization disabled. I'll refer to this thread if other users have similar issues.

**Comment by paulle** [comment]
Screenshots

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
