### ISSUE TITLE
second decimal place showing temperature is useless

### ISSUE THREAD

**Issue by paulle** [TylerWilliamson/BatteryNotification#6]
What do you think about:
The second decimal place showing the temperature is useless because it's always zero.
It would be a 'cleaner' look, when it's deleted. Maybe the first decimal place too.
I know that's only cosmetic.
As I have no programming skills
I don't know if this is easy to do or not.
![Screenshot_20220515-110226](https://user-images.githubusercontent.com/4852079/168466056-e2df9d9d-1608-4d68-9805-54bf2c947a51.png)

**Comment by TylerWilliamson** [comment]
This is a planned update which should be included in a future release

**Comment by TylerWilliamson** [comment]
Fixed in version [1.4.4](https://github.com/TylerWilliamson/BatteryNotification/releases/tag/1.4.4)
