### ISSUE TITLE
Reported Ampere Reversed

### ISSUE THREAD

**Issue by mxvin** [TylerWilliamson/BatteryNotification#7]
Hi, First of all, thanks for making this app, It's super simple and lightweight. 😃
I found a little problem, that app shows ampere when charge in negative number, but when discharge it reports positive number.
here's the illustration:
![photo_2022-06-08_11-19-03](https://user-images.githubusercontent.com/16519644/172531497-6aeed7fd-7922-48c0-8c86-345d3d50d3fd.jpg)
SS on #6 
<img src="https://user-images.githubusercontent.com/4852079/168466056-e2df9d9d-1608-4d68-9805-54bf2c947a51.png" height="1000px" />
OS is Lineage 17.1 Android 10
App version 1.4.3 / latest

Thanks

FINAL INVESTIGATION
You're wrong on these logic
https://github.com/TylerWilliamson/BatteryNotification/blob/e201b6a30f17b294d32c12aa1af5d213e24634c3/app/src/main/java/com/ominous/batterynotification/util/BatteryUtils.java#L119

`const BATTERY_STATUS_CHARGING = 2` and `const BATTERY_STATUS_DISCHARGING = 3` so the first `IF true = 1` not `-1`

`int batteryCurrent = (intent.getIntExtra(BatteryManager.EXTRA_STATUS, -1) == BatteryManager.BATTERY_STATUS_CHARGING ? 1 : -1)`

**Comment by TylerWilliamson** [comment]
You are correct. I was overcomplicating the logic. I'll be removing the ternary statement and the charging sign will be whatever the device is outputting. Expect the change in the next release.

**Comment by TylerWilliamson** [comment]
Fixed in [1.4.4](https://github.com/TylerWilliamson/BatteryNotification/releases/tag/1.4.4)
